# Generated by Django 4.0.6 on 2022-07-22 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='science/')),
            ],
        ),
        migrations.CreateModel(
            name='LogColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webLog.logfile')),
            ],
        ),
    ]
