# Generated by Django 4.1 on 2023-02-07 05:25

from django.db import migrations, models
import webLog.models


class Migration(migrations.Migration):

    dependencies = [
        ("webLog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logfile",
            name="file",
            field=models.FileField(upload_to=webLog.models.get_file_path),
        ),
    ]
