# Generated by Django 4.0.6 on 2022-07-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webLog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='LogFile',
        ),
    ]
