# Generated by Django 4.0.6 on 2022-07-15 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webLog', '0002_rename_log_logfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=200)),
                ('logfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webLog.logfile')),
            ],
        ),
    ]
