# Generated by Django 4.0.6 on 2022-07-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webLog', '0003_logcolumn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logcolumn',
            old_name='column',
            new_name='name',
        ),
    ]
