# Generated by Django 3.2.8 on 2022-12-26 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mechanical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saswellname',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='hsd_balance',
            old_name='tank1',
            new_name='closing_bal',
        ),
        migrations.RenameField(
            model_name='hsd_balance',
            old_name='tank2',
            new_name='consumption',
        ),
        migrations.RemoveField(
            model_name='drillshift',
            name='shifttype',
        ),
        migrations.RemoveField(
            model_name='electricalshift',
            name='shifttype',
        ),
        migrations.AddField(
            model_name='drillrig',
            name='shifttype',
            field=models.CharField(choices=[('Day Shift', 'First Shift'), ('Night Shift', 'Second Shift')], default='Day Shift', max_length=50),
        ),
        migrations.AddField(
            model_name='electricalrig',
            name='electrical_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanical.electricalshift'),
        ),
        migrations.AddField(
            model_name='electricalrig',
            name='shifttype',
            field=models.CharField(choices=[('Day Shift', 'First Shift'), ('Night Shift', 'Second Shift')], default='Day Shift', max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equip_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equip_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='today_equip',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipmentservice',
            name='service_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipmentservice',
            name='service_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentservice',
            name='today_equip_service',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hsd_balance',
            name='hsd_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hsd_balance',
            name='hsd_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hsd_balance',
            name='opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='hsd_balance',
            name='received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='hsd_balance',
            name='tank',
            field=models.CharField(blank=True, choices=[('tank1', 'Tank 1'), ('tank2', 'Tank 2')], default='tank1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hsd_balance',
            name='today_hsdbal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rig',
            name='daterig',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rig',
            name='equipment_singlehit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_singlehit', to='mechanical.equipment'),
        ),
        migrations.AddField(
            model_name='rig',
            name='hsdbalance_singlehit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hsdbalance_singlehit', to='mechanical.hsd_balance'),
        ),
        migrations.AddField(
            model_name='rig',
            name='rigdown_singlehit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rigdown_singlehit', to='mechanical.rigdown'),
        ),
        migrations.AddField(
            model_name='rig',
            name='service_singlehit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_singlehit', to='mechanical.equipmentservice'),
        ),
        migrations.AddField(
            model_name='rig',
            name='today_rig',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rig',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rigdown',
            name='rigdown_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rigdown',
            name='rigdown_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rigdown',
            name='today_rigdown',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='electricalshift',
            name='equipstatus',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT OK', 'NOT OK')], default='OK', max_length=50),
        ),
        migrations.AlterField(
            model_name='rig',
            name='shift',
            field=models.CharField(blank=True, choices=[('Day Shift', 'Shift-I'), ('Night Shift', 'Shift-II')], default='Day Shift', max_length=50, null=True),
        ),
    ]
