# Generated by Django 4.1 on 2023-01-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0003_auto_20230102_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalshift',
            name='shifttype',
            field=models.CharField(blank=True, choices=[('Day Shift', 'First Shift'), ('Night Shift', 'Second Shift')], default='Day Shift', max_length=50, null=True),
        ),
    ]
