# Generated by Django 4.1 on 2023-01-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0004_alter_electricalshift_shifttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drillshift',
            name='shifttype',
        ),
        migrations.AddField(
            model_name='drillrig',
            name='shifttype',
            field=models.CharField(blank=True, choices=[('Day Shift', 'First Shift'), ('Night Shift', 'Second Shift')], default='Day Shift', max_length=50, null=True),
        ),
    ]
