# Generated by Django 4.0.6 on 2022-07-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
