# Generated by Django 4.1 on 2022-11-28 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalrunninghours',
            name='runninghours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
    ]
