# Generated by Django 4.0.6 on 2022-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('well', models.CharField(blank=True, max_length=50, null=True)),
                ('shift', models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], default='Day', max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
