# Generated by Django 4.1 on 2022-08-12 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalrunninghours',
            name='electrical_rig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanical.electricalrig'),
        ),
        migrations.AddField(
            model_name='electricalshift',
            name='electrical_rig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanical.electricalrig'),
        ),
    ]
