# Generated by Django 4.0.6 on 2022-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0002_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rig',
            name='slug',
        ),
        migrations.AlterField(
            model_name='rig',
            name='shift',
            field=models.CharField(blank=True, choices=[('Day Shift', 'First Shift'), ('Night Shift', 'Second Shift')], default='Day', max_length=50, null=True),
        ),
    ]
