# Generated by Django 4.1 on 2022-08-12 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0002_electricalrunninghours_electrical_rig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drilldata',
            name='rig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanical.drillrig'),
        ),
        migrations.AddField(
            model_name='drilllaboratory',
            name='rig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanical.drillrig'),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='rig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanical.drillrig'),
        ),
        migrations.AddField(
            model_name='hydraulicdata',
            name='rig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanical.drillrig'),
        ),
    ]
