# Generated by Django 4.1 on 2022-12-05 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocrFile', '0001_initial'),
        ('mechanical', '0002_alter_electricalrig_well'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocrFile.upload'),
        ),
    ]
