# Generated by Django 4.1 on 2023-02-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mechanical",
            "0002_alter_electricalrig_date_alter_electricalrig_doc_no_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricalrig",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
