# Generated by Django 4.1 on 2022-08-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0003_drilldata_rig_drilllaboratory_rig_drillshift_rig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillSolidControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaleshaker', models.IntegerField(default=0)),
                ('desander', models.IntegerField(default=0)),
                ('desilter', models.IntegerField(default=0)),
                ('degasser', models.IntegerField(default=0)),
                ('mudlcleaner', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('rig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanical.drillrig')),
            ],
        ),
        migrations.CreateModel(
            name='DrillMudVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shalevole', models.IntegerField(default=0)),
                ('shalespgr', models.IntegerField(default=0)),
                ('settingvole', models.IntegerField(default=0)),
                ('settingspgr', models.IntegerField(default=0)),
                ('intervole', models.IntegerField(default=0)),
                ('interspgr', models.IntegerField(default=0)),
                ('suctionvole', models.IntegerField(default=0)),
                ('suctionspgr', models.IntegerField(default=0)),
                ('tank1vole', models.IntegerField(default=0)),
                ('tank1spgr', models.IntegerField(default=0)),
                ('tank2vole', models.IntegerField(default=0)),
                ('tank2spgr', models.IntegerField(default=0)),
                ('rig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanical.drillrig')),
            ],
        ),
        migrations.CreateModel(
            name='DrillMudChemicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('unit', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('opening', models.IntegerField(default=0)),
                ('receipt', models.IntegerField(default=0)),
                ('consumption', models.IntegerField(default=0)),
                ('closing', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('rig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanical.drillrig')),
            ],
        ),
    ]
