# Generated by Django 4.1 on 2022-12-02 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0003_remove_electricalrunninghours_hours_0_24_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalshift',
            name='runninghours_prev',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equip_avail_hour',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equip_working_hour',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='equipmentservice',
            name='avail_hour',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='equipmentservice',
            name='working_hour',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.DeleteModel(
            name='Electricalrunninghours',
        ),
    ]
