# Generated by Django 4.1 on 2022-08-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0004_drillsolidcontrol_drillmudvolume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricalrunninghours',
            old_name='electrical_rig',
            new_name='rig',
        ),
        migrations.RenameField(
            model_name='electricalshift',
            old_name='electrical_rig',
            new_name='rig',
        ),
    ]
