# Generated by Django 4.1 on 2023-02-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanical", "0004_alter_electricalrig_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricalshift",
            name="energydg1",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="electricalshift",
            name="energydg2",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="electricalshift",
            name="energydg3",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="electricalshift",
            name="energydg4",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
