# Generated by Django 4.0.6 on 2022-07-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0004_rig_mech_engineer_rig_requirements_alter_rig_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='name',
            new_name='equip_name',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='oil_used',
            new_name='equip_oil_used',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='working_hour',
            new_name='equip_working_hour',
        ),
        migrations.RenameField(
            model_name='equipmentservice',
            old_name='equi_avail_hour',
            new_name='avail_hour',
        ),
        migrations.RenameField(
            model_name='equipmentservice',
            old_name='name',
            new_name='equip_serv_name',
        ),
        migrations.RemoveField(
            model_name='rig',
            name='name',
        ),
        migrations.AddField(
            model_name='rig',
            name='rig_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='well',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
