# Generated by Django 4.1 on 2022-08-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0005_rename_electrical_rig_electricalrunninghours_rig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalrunninghours',
            name='runninghours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
