# Generated by Django 4.0.6 on 2022-07-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0005_rename_name_equipment_equip_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='equi_avail_hour',
            new_name='equip_avail_hour',
        ),
    ]
