# Generated by Django 4.1 on 2022-08-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanical', '0006_alter_electricalrunninghours_runninghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalrunninghours',
            name='runninghours',
            field=models.IntegerField(default=0),
        ),
    ]
