# Generated by Django 4.1 on 2023-02-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanical", "0006_alter_electricalshift_energydg1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricalshift",
            name="equipdetails",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Alternator-1,1430kVA, KATO Make",
                        "Alternator-1,1430kVA, KATO Make",
                    ),
                    (
                        "Alternator-2,1430kVA, KATO Make",
                        "Alternator-2,1430kVA, KATO Make",
                    ),
                    (
                        "Alternator-3,1430kVA, KATO Make",
                        "Alternator-3,1430kVA, KATO Make",
                    ),
                    (
                        "Alternator-4,1430kVA, KATO Make",
                        "Alternator-4,1430kVA, KATO Make",
                    ),
                    (
                        "Emg. DG Set Alternator, 400kVA",
                        "Emg. DG Set Alternator, 400kVA",
                    ),
                    ("HPU Motor (Main)-1,750HP", "HPU Motor (Main)-1,750HP"),
                    ("HPU Motor (Main)-2,750HP", "HPU Motor (Main)-2,750HP"),
                    (
                        "HPU1 supercharger Motor-1,40HP",
                        "HPU1 supercharger Motor-1,40HP",
                    ),
                    (
                        "HPU1 supercharger Motor-2,40HP",
                        "HPU1 supercharger Motor-2,40HP",
                    ),
                    (
                        "HPU2 supercharger Motor-1,40HP",
                        "HPU2 supercharger Motor-1,40HP",
                    ),
                    (
                        "HPU2 supercharger Motor-2,40HP",
                        "HPU2 supercharger Motor-2,40HP",
                    ),
                    ("Mud Pump Motor(Main)-1,1600HP", "Mud Pump Motor(Main)-1,1600HP"),
                    ("Mud Pump Motor(Main)-2,1600HP", "Mud Pump Motor(Main)-2,1600HP"),
                    ("MP1 Blower Motor,25HP", "MP1 Blower Motor,25HP"),
                    (
                        "MP1 Liner Cooling Pump Motor,3HP",
                        "MP1 Liner Cooling Pump Motor,3HP",
                    ),
                    ("MP1 Lube Oil Pump Motor,4HP", "MP1 Lube Oil Pump Motor,4HP"),
                    ("MP2 Blower Motor,25HP", "MP2 Blower Motor,25HP"),
                    (
                        "MP2 Liner Cooling Pump Motor,3HP",
                        "MP2 Liner Cooling Pump Motor,3HP",
                    ),
                    ("MP2 Lube Oil Pump Motor,4HP", "MP2 Lube Oil Pump Motor,4HP"),
                    (
                        "Pipe Handler Clamp Motor,1.2kW",
                        "Pipe Handler Clamp Motor,1.2kW",
                    ),
                    (
                        "Pipe Handler Lower Arm Motor,1.5kW",
                        "Pipe Handler Lower Arm Motor,1.5kW",
                    ),
                    (
                        "Pipe Handler Rotation Motor,11kW",
                        "Pipe Handler Rotation Motor,11kW",
                    ),
                    (
                        "Electrical Air Compressor Motor,100HP",
                        "Electrical Air Compressor Motor,100HP",
                    ),
                    ("BOP Koomy Control Motor,30HP", "BOP Koomy Control Motor,30HP"),
                    ("Rig Up HPU Motor", "Rig Up HPU Motor"),
                    (
                        "Mud Supercharger Motor-1,100HP",
                        "Mud Supercharger Motor-1,100HP",
                    ),
                    (
                        "Mud Supercharger Motor-2,100HP",
                        "Mud Supercharger Motor-2,100HP",
                    ),
                    (
                        "Hopper (Mud Mixer) Motor-1,100HP",
                        "Hopper (Mud Mixer) Motor-1,100HP",
                    ),
                    (
                        "Hopper (Mud Mixer) Motor-2,100HP",
                        "Hopper (Mud Mixer) Motor-2,100HP",
                    ),
                    (
                        "Ground Water Pump Motor-1,30HP (ULMMC) Motor,100HP",
                        "Ground Water Pump Motor-1,30HP (ULMMC) Motor,100HP",
                    ),
                    ("Desilter (ULMMC) Motor,100HP", "Desilter (ULMMC) Motor,100HP"),
                    ("Trip Tank Motor-1,20HP", "Trip Tank Motor-1,20HP"),
                    ("Trip Tank Motor-2,20HP", "Trip Tank Motor-2,20HP"),
                    ("Still Tank Water Motor-1,30HP", "Still Tank Water Motor-1,30HP"),
                    ("Still Tank Water Motor-2,30HP", "Still Tank Water Motor-2,30HP"),
                    (
                        "Ground Water Pump Motor-1,30HP",
                        "Ground Water Pump Motor-1,30HP",
                    ),
                    (
                        "Ground Water Pump Motor-2,30HP",
                        "Ground Water Pump Motor-2,30HP",
                    ),
                    ("HP Wasing Unit Motor-1,20HP", "HP Wasing Unit Motor-1,20HP"),
                    ("HP Wasing Unit Motor-2,20HP", "HP Wasing Unit Motor-2,20HP"),
                    ("Shale Shaker Motor-1,2SHP", "Shale Shaker Motor-1,2SHP"),
                    ("Shale Shaker Motor-2,2SHP", "Shale Shaker Motor-2,2SHP"),
                    ("Shale Shaker Motor-3,2SHP", "Shale Shaker Motor-3,2SHP"),
                    ("Mud Cleaner Motor,2SHP", "Mud Cleaner Motor,2SHP"),
                    ("Vaccum Degasser Motor,5HP", "Vaccum Degasser Motor,5HP"),
                    ("Agitator Motor-1,25HP", "Agitator Motor-1,25HP"),
                    ("Agitator Motor-2,25HP", "Agitator Motor-2,25HP"),
                    ("Agitator Motor-4,25HP", "Agitator Motor-4,25HP"),
                    ("Agitator Motor-5,25HP", "Agitator Motor-5,25HP"),
                    ("Agitator Motor-6,25HP", "Agitator Motor-6,25HP"),
                    ("Agitator Motor-7,25HP", "Agitator Motor-7,25HP"),
                    ("Agitator Motor-8,25HP", "Agitator Motor-8,25HP"),
                    ("Agitator Motor-9,25HP", "Agitator Motor-9,25HP"),
                    ("Agitator Motor-10,25HP", "Agitator Motor-10,25HP"),
                    ("Agitator Motor-11,25HP", "Agitator Motor-11,25HP"),
                    ("Agitator Motor-12,25HP", "Agitator Motor-12,25HP"),
                    ("Agitator Motor-13,25HP", "Agitator Motor-13,25HP"),
                    ("Agitator Motor-14,25HP", "Agitator Motor-14,25HP"),
                    ("Agitator Motor-15,25HP", "Agitator Motor-15,25HP"),
                    ("Agitator Motor-16,25HP", "Agitator Motor-16,25HP"),
                    ("Fuel Receiving Pump-1(U),3HP", "Fuel Receiving Pump-1(U),3HP"),
                    ("Fuel Receiving Pump-2(U),3HP", "Fuel Receiving Pump-2(U),3HP"),
                    ("Fuel Transfer Pump-1(L),5HP", "Fuel Transfer Pump-1(L),5HP"),
                    ("Fuel Transfer Pump-2(L),5HP", "Fuel Transfer Pump-2(L),5HP"),
                    ("Radiator Motor-1,60HP", "Radiator Motor-1,60HP"),
                    ("Radiator Motor-2,60HP", "Radiator Motor-2,60HP"),
                    ("Radiator Motor-3,60HP", "Radiator Motor-3,60HP"),
                    ("Radiator Motor-4,60HP", "Radiator Motor-4,60HP"),
                    ("Drilling PCR HVAC", "Drilling PCR HVAC"),
                    ("MUD PCR HVAC", "MUD PCR HVAC"),
                    ("600V System", "600V System"),
                    ("Mobile Welding Set", "Mobile Welding Set"),
                    ("Welding Rectifier/Transformer", "Welding Rectifier/Transformer"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
