EQUIP_NAME = (
        ('Carrier Engine - 1', 'Carrier Engine - 1'),
        ('Carrier Engine - 2', 'Carrier Engine - 2'),
        ('MP Engine - 1', 'MP Engine - 1'),
        ('MP Engine - 2', 'MP Engine - 2'),
        ('DG SET Engine - 1', 'DG SET Engine - 1'),
        ('DG SET Engine - 2', 'DG SET Engine - 2'),
        ('DG SET Engine - 3', 'DG SET Engine - 3'),
        ('DG SET Engine - 4', 'DG SET Engine - 4'),
        ('Transmission CE - 1', 'Transmission CE - 1'),
        ('Transmission CE - 2', 'Transmission CE - 2'),
        ('Compresser (Elect.) - 1', 'Compresser (Elect.) - 1'),
        ('Compresser (Elect.) - 2', 'Compresser (Elect.) - 2'),
        ('Compresser (Mech.) - 1', 'Compresser (Mech.) - 1'),
        ('Compresser (Mech.) - 2', 'Compresser (Mech.) - 2'),
        ('Diesel Engine Comp.(Mech.) - 1', 'Compresser(Mech.) - 2'),
        ('Diesel Engine Comp.(Mech.) - 2', 'Diesel Engine Comp.(Mech.) - 2'),
        ('Mud Pump - 1', 'Mud Pump - 1'),
        ('Mud Pump - 2', 'Mud Pump - 2'),
        ('Torque Converter MP1', 'Torque Converter MP1'),
        ('Torque Converter MP1', 'Torque Converter MP1'),
        ('Fire Water Pump', 'Fire Water Pump'),
        ('Power Take - Off - 1', 'Power Take - Off - 1'),
        ('Power Take - Off - 2', 'Power Take - Off - 2'),
        ('Draw Works', 'Draw Works'),
        ('Rotary / Bevel Gear Box', 'Rotary / Bevel Gear Box'),
        ('C/B T/B - Hook', 'C/B T/B - Hook'),
        ('Swivel', 'Swivel'),
        ('Shale Shaker Bucket - 1', 'Shale Shaker Bucket - 1'),
        ('Shale Shaker Bucket - 2', 'Shale Shaker Bucket - 2'),
        ('R/T /Rotary Elevator Drive', 'R/T /Rotary Elevator Drive'),
        ('Hydromatic Brake', 'Hydromatic Brake'),
        ('Super Charger - 1', 'Super Charger - 1'),
        ('Super Charger - 2', 'Super Charger - 2'),
        ('Hopper Pump - 1', 'Hopper Pump - 1'),
        ('Hopper Pump - 2', 'Hopper Pump - 2'),
        ('Degasser', 'Degasser'),
        ('Desander', 'Desander'),
        ('Mud Cleaner', 'Mud Cleaner'),
        ('Desander Pump', 'Desander Pump'),
        ('Desilter Pump', 'Desilter Pump'),
        ('Ezy Torque', 'Ezy Torque'),
        ('Pipe Spinner', 'Pipe Spinner'),
        ('Kelly Spinner', 'Kelly Spinner'),
        ('Main Water Pump', 'Main Water Pump'),
        ('Second Water Pump', 'Second Water Pump'),
        ('Air Winch', 'Air Winch'),
        ('Mud Agitator - 1', 'Mud Agitator - 1'),
        ('Mud Agitator - 2', 'Mud Agitator - 2'),
        ('Mud Agitator - 3', 'Mud Agitator - 3'),
        ('Mud Agitator - 4', 'Mud Agitator - 4'),
        ('Mud Agitator - 5', 'Mud Agitator - 5'),
        ('Mud Agitator - 6', 'Mud Agitator - 6'),
        ('Mud Agitator - 7', 'Mud Agitator - 7'),
        ('Mud Agitator - 8', 'Mud Agitator - 8'),
        ('Mud Agitator - 9', 'Mud Agitator - 9'),
        ('Mud Agitator - 10', 'Mud Agitator - 10'),
        ('Mud Agitator - 11', 'Mud Agitator - 11'),
        ('Mud Agitator - 12', 'Mud Agitator - 12'),
    )
