# Generated by Django 4.1 on 2022-11-04 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='pdf',
            field=models.FileField(blank=True, upload_to='ocr/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
